export const ErrorTypes = {
    INVALID_DATE: "INVALID_DATE",
    UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
    LOG_FILE_NOT_FOUND: "LOG_FILE_NOT_FOUND"
}

export const StatusCode = {
    OK : 200,
    BAD_REQUEST : 400,
    NOT_FOUND : 404,
    INTERNAL_SERVER_ERROR : 500
}