name: Quality Assurance GitHub Actions Workflow

on:
  pull_request:
    branches: [development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch the last 2 commits

    - name: Fetch all history for all branches and tags
      run: |
        if [ $(git rev-parse --is-shallow-repository) == "true" ]; then
          git fetch --prune --unshallow
        else
          git fetch --prune
        fi

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV

        echo "Previous commit: $previous_commit"
        echo "Current commit: $current_commit"

    - name: Check for folder changes and run tests
      run: |
        echo "Checking changes between commits $previous_commit and $current_commit"
        changed_files=$(git diff --name-only $previous_commit $current_commit)
        echo "Changed files: $changed_files"
        for folder in $(find . -type d -name "__tests__" | cut -d'/' -f2 | sort -u); do
          if echo "$changed_files" | grep -q "^$folder/"; then
            echo "$folder has changes in __tests__"
            echo "Running npm test in $folder"
            cd $folder
            npm install
            npm run test
            cd ..
          fi
        done

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch the last 2 commits

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Fetch all history for all branches and tags
      run: |
        if [ $(git rev-parse --is-shallow-repository) == "true" ]; then
          git fetch --prune --unshallow
        else
          git fetch --prune
        fi

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV

        echo "Previous commit: $previous_commit"
        echo "Current commit: $current_commit"

    - name: Check for folder changes and run coverage
      run: |
        echo "Checking changes between commits $previous_commit and $current_commit"
        changed_files=$(git diff --name-only $previous_commit $current_commit)
        echo "Changed files: $changed_files"
        for folder in $(find . -type d -name "__tests__" | cut -d'/' -f2 | sort -u); do
          if echo "$changed_files" | grep -q "^$folder/"; then
            echo "$folder has changes in __tests__"
            echo "Running npm coverage in $folder"
            cd $folder
            npm install
            npm run coverage
            cd ..
          fi
        done
        
  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check Title Format
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(feat|fix|refactor|docs|test):\s\[\w+-\d+\]\s.+$'
          github_token: ${{ secrets.GITHUB_TOKEN }}
