name: Quality Assurance GitHub Actions Workflow

on:
  pull_request:
    branches: [development]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV
    - uses: actions/setup-node@v1
      with:
        node-version: '20'
    - name: Check for folder changes and run tests
      run: |
        echo "Checking changes between commits $previous_commit and $current_commit"
        for folder in $(ls -d */ | cut -f1 -d'/'); do
          if git diff --name-only $previous_commit $current_commit | grep -q "^$folder/"; then
            echo "$folder has changed"
            echo "Running npm test in $folder"
            cd $folder
            npm install
            npm run test
            cd ..
          fi
        done

  coverage:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV

    - name: Check for folder changes and run coverage
      run: |
        echo "Checking changes between commits $previous_commit and $current_commit"
        for folder in $(ls -d */ | cut -f1 -d'/'); do
          if git diff --name-only $previous_commit $current_commit | grep -q "^$folder/"; then
            echo "$folder has changed"
            echo "Running npm coverage in $folder"
            cd $folder
            npm install
            npm run coverage
            cd ..
          fi
        done
    - name: Code Coverage Report
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        github-token: ${{ secrets.GH_PAT }}
        lcov-file: ./coverage/lcov.info
        delete-old-comments: true
  
  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check Title Format
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(feat|fix|refactor|docs|test):\s\[\w+-\d+\]\s.+$'
          github_token: ${{ secrets.GITHUB_TOKEN }}