name: Quality Assurance GitHub Actions Workflow

on:
  pull_request:
    branches: [development]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV
    - uses: actions/setup-node@v1
      with:
       node-version: 20
    - name: Set execute permissions for run_tests.sh
      run: chmod +x .github/scripts/run_tests.sh

    - name: Check for folder changes and run tests
      run: .github/scripts/run_tests.sh ${{ env.previous_commit }} ${{ env.current_commit }}

  coverage:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV

    - name: Set execute permissions for run_coverage.sh
      run: chmod +x .github/scripts/run_coverage.sh
    - name: Code Coverage Report
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        github-token: ${{ secrets.GH_PAT }}
        lcov-file: ./coverage/lcov.info
        delete-old-comments: true

    - name: Check for folder changes and run coverage
      run: .github/scripts/run_coverage.sh ${{ env.previous_commit }} ${{ env.current_commit }}

  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check Title Format
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(feat|fix|refactor|docs|test):\s\[\w+-\d+\]\s.+$'
          github_token: ${{ secrets.GITHUB_TOKEN }}


  security-check:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run npm audit
        run: npm audit --audit-level=high
        continue-on-error: true
