name: Quality Assurance GitHub Actions Workflow

on:
  pull_request:
    branches: [development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch only the last 2 commits

    - name: Determine the commit range
      id: commit_range
      run: |
        base_commit=$(jq -r '.pull_request.base.sha' < $GITHUB_EVENT_PATH)
        head_commit=$(jq -r '.pull_request.head.sha' < $GITHUB_EVENT_PATH)

        echo "base_commit=$base_commit" >> $GITHUB_ENV
        echo "head_commit=$head_commit" >> $GITHUB_ENV

        echo "Base commit: $base_commit"
        echo "Head commit: $head_commit"

    - name: Check for folder changes and run tests
      run: |
        echo "Checking changes between commits $base_commit and $head_commit"
        changed_files=$(git diff --name-only $base_commit $head_commit)
        echo "Changed files: $changed_files"
        for folder in $(find . -type d -name "__tests__" | cut -d'/' -f2 | sort -u); do
          if echo "$changed_files" | grep -q "^$folder/"; then
            echo "$folder has changes in __tests__"
            echo "Running npm test in $folder"
            cd $folder
            npm install
            npm run test
            cd ..
          fi
        done

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch only the last 2 commits

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Determine the commit range
      id: commit_range
      run: |
        base_commit=$(jq -r '.pull_request.base.sha' < $GITHUB_EVENT_PATH)
        head_commit=$(jq -r '.pull_request.head.sha' < $GITHUB_EVENT_PATH)

        echo "base_commit=$base_commit" >> $GITHUB_ENV
        echo "head_commit=$head_commit" >> $GITHUB_ENV

        echo "Base commit: $base_commit"
        echo "Head commit: $head_commit"

    - name: Check for folder changes and run coverage
      run: |
        echo "Checking changes between commits $base_commit and $head_commit"
        changed_files=$(git diff --name-only $base_commit $head_commit)
        echo "Changed files: $changed_files"
        for folder in $(find . -type d -name "__tests__" | cut -d'/' -f2 | sort -u); do
          if echo "$changed_files" | grep -q "^$folder/"; then
            echo "$folder has changes in __tests__"
            echo "Running npm coverage in $folder"
            cd $folder
            npm install
            npm run coverage
            cd ..
          fi
        done
        
  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check Title Format
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(feat|fix|refactor|docs|test):\s\[\w+-\d+\]\s.+$'
          github_token: ${{ secrets.GITHUB_TOKEN }}
