name: Quality Assurance GitHub Actions Workflow

on:
  pull_request:
    branches: [development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV

    - name: Set execute permissions for detect_changed_folders.sh
      run: chmod +x .github/scripts/detect_changed_folders.sh

    - name: Detect changed folders
      id: detect_changed_folders
      run: |
        changed_folders=$(./.github/scripts/detect_changed_folders.sh ${{ env.previous_commit }} ${{ env.current_commit }})
        echo "$changed_folders" | tr '\n' ' ' > changed_folders.txt

    - name: Run npm test in changed folders
      run: |
        while read -r folder; do
          echo "$folder has changed"
          echo "Running npm test in $folder"
          cd $folder
          npm install
          npm run test
          cd ..
        done < changed_folders.txt

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV

    - name: Set execute permissions for detect_changed_folders.sh
      run: chmod +x .github/scripts/detect_changed_folders.sh

    - name: Detect changed folders
      id: detect_changed_folders
      run: |
        changed_folders=$(./.github/scripts/detect_changed_folders.sh ${{ env.previous_commit }} ${{ env.current_commit }})
        echo "$changed_folders" | tr '\n' ' ' > changed_folders.txt

    - name: Run npm coverage in changed folders
      run: |
        while read -r folder; do
          echo "$folder has changed"
          echo "Running npm coverage in $folder"
          cd $folder
          npm install
          npm run coverage
          cd ..
        done < changed_folders.txt

  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check Title Format
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(feat|fix|refactor|docs|test):\s\[\w+-\d+\]\s.+$'
          github_token: ${{ secrets.GITHUB_TOKEN }}
