name: Log Changed Folder

on:
  push:
    paths:
      - 'CommonMessages/**'
      - 'Logger/**'
      - 'RabbitMqClient/**'
      - 'RedisClient/**'
      - 'Supervision/**'
  pull_request:
    paths:
      - 'CommonMessages/**'
      - 'Logger/**'
      - 'RabbitMqClient/**'
      - 'RedisClient/**'
      - 'Supervision/**'

jobs:
  log_changed_folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log changed folder
      id: detect-changes
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^CommonMessages/'; then
          echo "::set-output name=folder::CommonMessages"
        elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^Logger/'; then
          echo "::set-output name=folder::Logger"
        elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^RabbitMqClient/'; then
          echo "::set-output name=folder::RabbitMqClient"
        elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^RedisClient/'; then
          echo "::set-output name=folder::RedisClient"
        elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^Supervision/'; then
          echo "::set-output name=folder::Supervision"
        else
          echo "::set-output name=folder::None"

    - name: Log the changed folder
      run: echo "The changed folder is ${{ steps.detect-changes.outputs.folder }}"
