name: Run Tests and Coverage

on:
  push:
    branches:
      - development

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Get list of changed files
        id: changes
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')"

      - name: Set changed folders
        id: folders
        run: |
          FILES=${{ steps.changes.outputs.files }}
          FOLDERS=$(echo "$FILES" | tr ' ' '\n' | grep -E '^(CommonMessages|Logger|RabbitMqClient|RedisClient|Supervision)/' | cut -d/ -f1 | sort | uniq)
          echo "::set-output name=folders::${FOLDERS}"

      - name: Run tests and coverage
        run: |
          for folder in ${{ steps.folders.outputs.folders }}; do
            cd $folder/__tests__
            npm run test
            npm run coverage
            cd ../..
          done
