name: Run Tests and Coverage

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [CommonMessages, Logger, RabbitMqClient, RedisClient, Supervision]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          cd ${{ matrix.folder }}/__tests__
          npm run test

      - name: Run coverage
        run: |
          cd ${{ matrix.folder }}/__tests__
          npm run coverage
