name: Folder Changes

on: [push]

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV

    - name: Set up matrix for changed folders
      id: set_matrix
      run: |
        folders=("CommonMessages" "Logger" "RedisClient" "RabbitMqClient" "Supervision")
        jobs_matrix=""

        for folder in "${folders[@]}"; do
          if git diff --name-only $previous_commit $current_commit | grep -q "^$folder/"; then
            jobs_matrix="$jobs_matrix{\"folder\": \"$folder\", \"job\": \"test\"},"
            jobs_matrix="$jobs_matrix{\"folder\": \"$folder\", \"job\": \"coverage\"},"
          fi
        done

        # Remove the trailing comma
        jobs_matrix="[${jobs_matrix%,}]"
        echo "jobs_matrix=$jobs_matrix" >> $GITHUB_ENV

    - name: Save matrix
      id: save_matrix
      run: echo "${{ env.jobs_matrix }}"

  dynamic_jobs:
    runs-on: ubuntu-latest
    needs: test_and_coverage
    strategy:
      matrix:
        config: ${{ fromJson(needs.test_and_coverage.outputs.jobs_matrix) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run job
      run: |
        cd ${{ matrix.config.folder }}
        npm install
        if [ "${{ matrix.config.job }}" == "test" ]; then
          npm run test
        else
          npm run coverage
        fi
