name: Folder Changes

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Setup script permissions
      run: chmod +x ./check-and-run.sh

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV

    - name: Check for folder changes and run tests
      run: ./check-and-run.sh test

  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Setup script permissions
      run: chmod +x ./check-and-run.sh

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV

    - name: Check for folder changes and run coverage
      run: ./check-and-run.sh coverage
