name: Run Tests and Coverage

on:
  push:
    paths:
      - '**/CommonMessages/**'
      - '**/Logger/**'
      - '**/RabbitMqClient/**'
      - '**/RedisClient/**'
      - '**/Supervision/**'
  pull_request:
    paths:
      - '**/CommonMessages/**'
      - '**/Logger/**'
      - '**/RabbitMqClient/**'
      - '**/RedisClient/**'
      - '**/Supervision/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Determine changed folder
      id: determine_folder
      run: |
        CHANGED_FOLDER=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -oE '^(\S+)/' | head -1)
        echo "::set-output name=folder::$CHANGED_FOLDER"

    - name: Run tests and coverage
      if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') }}
      run: |
        cd ${{ steps.determine_folder.outputs.folder }}
        npm install
        npm install ts-node --save-dev
        cd __tests__
        npm run test
        npm run coverage
