name: Run Tests and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [CommonMessages, Logger, RabbitMqClient, RedisClient, Supervision]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests and coverage for ${{ matrix.folder }}
      run: |
        cd ${{ matrix.folder }}
        npm install
        cd __tests__
        npm run test
        npm run coverage 
