name: Run Tests and Coverage

on:
  push:
    branches:
      - development

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get list of changed files
        id: changes
        run: |
          git fetch origin development
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=files::$CHANGED_FILES"

      - name: Set changed folders
        id: folders
        run: |
          FILES="${{ steps.changes.outputs.files }}"
          echo "Files changed: $FILES"
          FOLDERS=$(echo "$FILES" | tr ' ' '\n' | grep -E '^(CommonMessages|Logger|RabbitMqClient|RedisClient|Supervision)/' | cut -d/ -f1 | sort | uniq)
          echo "Folders detected: $FOLDERS"
          echo "::set-output name=folders::$FOLDERS"

      - name: Run tests and coverage
        run: |
          FOLDERS="${{ steps.folders.outputs.folders }}"
          echo "Running tests for folders: $FOLDERS"
          for folder in $FOLDERS; do
            cd $folder
            echo "Installing dependencies in $folder"
            npm install
            cd __tests__
            echo "Running tests in $folder/__tests__"
            npm run test
            npm run coverage
            cd ../..
          done
