name: Run Tests and Coverage

on:
  push:
    paths:
      - '**/CommonMessages/**'
      - '**/Logger/**'
      - '**/RabbitMqClient/**'
      - '**/RedisClient/**'
      - '**/Supervision/**'
  pull_request:
    paths:
      - '**/CommonMessages/**'
      - '**/Logger/**'
      - '**/RabbitMqClient/**'
      - '**/RedisClient/**'
      - '**/Supervision/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [CommonMessages, Logger, RabbitMqClient, RedisClient, Supervision]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests and coverage for ${{ matrix.folder }}
      if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') }}
      run: |
        cd ${{ matrix.folder }}
        npm install
        npm install ts-node --save-dev
        cd __tests__
        npm run test
        npm run coverage
