name: Run Tests and Coverage

on:
  push:
    paths:
      - '**/CommonMessages/**'
      - '**/Logger/**'
      - '**/RabbitMqClient/**'
      - '**/RedisClient/**'
      - '**/Supervision/**'
  pull_request:
    paths:
      - '**/CommonMessages/**'
      - '**/Logger/**'
      - '**/RabbitMqClient/**'
      - '**/RedisClient/**'
      - '**/Supervision/**'

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      changed_folders: ${{ steps.detect_changes.outputs.changed_folders }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Detect changed folders
      id: detect_changes
      run: |
        CHANGED_FOLDERS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -oE '^(CommonMessages|Logger|RabbitMqClient|RedisClient|Supervision)' | sort -u)
        echo "Changed folders: $CHANGED_FOLDERS"
        echo "changed_folders=$CHANGED_FOLDERS" >> $GITHUB_ENV
        echo "::set-output name=changed_folders::$CHANGED_FOLDERS"

  test:
    needs: detect_changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [CommonMessages, Logger, RabbitMqClient, RedisClient, Supervision]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log changed folders
      run: |
        echo "Running tests for folders: ${{ env.changed_folders }}"

    - name: Run tests and coverage
      if: contains(env.changed_folders, matrix.folder)
      run: |
        cd ${{ matrix.folder }}
        npm install
        npm install ts-node --save-dev
        cd __tests__
        npm run test
        npm run coverage
