name: Folder Changes

on: [push]

jobs:
  determine_changed_folders:
    runs-on: ubuntu-latest
    outputs:
      changed_folders: ${{ steps.get_changed_folders.outputs.changed_folders }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Determine the changed folders
      id: get_changed_folders
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        folders=("CommonMessages" "Logger" "RedisClient" "RabbitMqClient" "Supervision")
        changed_folders=""

        for folder in "${folders[@]}"; do
          if git diff --name-only $previous_commit $current_commit | grep -q "^$folder/"; then
            changed_folders="$changed_folders,$folder"
          fi
        done

        changed_folders=${changed_folders:1}
        echo "::set-output name=changed_folders::$changed_folders"

  test:
    runs-on: ubuntu-latest
    needs: determine_changed_folders
    strategy:
      matrix:
        folder: ${{ fromJson(needs.determine_changed_folders.outputs.changed_folders) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        cd ${{ matrix.folder }}
        npm install
        npm run test

  coverage:
    runs-on: ubuntu-latest
    needs: determine_changed_folders
    strategy:
      matrix:
        folder: ${{ fromJson(needs.determine_changed_folders.outputs.changed_folders) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run coverage
      run: |
        cd ${{ matrix.folder }}
        npm install
        npm run coverage
