name: Run Tests and Coverage

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [CommonMessages, Logger, RabbitMqClient, RedisClient, Supervision]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install root dependencies
      run: npm install

    - name: Install package dependencies
      run: |
        cd ${{ matrix.folder }}
        npm install

    - name: Run tests
      run: |
        cd ${{ matrix.folder }}/__tests__
        npm run test
        npm run coverage
