name: Run Tests

on: 
  push:
    branches:
      - development


jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [CommonMessages, Logger, RabbitMqClient, RedisClient, Supervision]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the version of Node.js your project requires

      - name: Install dependencies
        run: npm install

      - name: Check for changes in ${{ matrix.folder }}
        id: changes
        run: |
          echo "Checking for changes in ${{ matrix.folder }}"
          if git diff --name-only HEAD^ HEAD | grep -q "^${{ matrix.folder }}/"; then
            echo "Changes detected in ${{ matrix.folder }}"
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "No changes detected in ${{ matrix.folder }}"
            echo "changed=false" >> $GITHUB_ENV

      - name: Run tests
        if: env.changed == 'true'
        run: |
          cd ${{ matrix.folder }}/__tests__
          npm run test
          npm run coverage
