name: Folder Changes

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV

    - name: Get all folders
      id: get_folders
      run: |
        folders=$(find . -maxdepth 1 -type d | sed 's|./||' | grep -v '^\.$' | grep -v '.git')
        echo "folders=$folders" >> $GITHUB_ENV
        echo "folders=$folders" > folders.txt

    - name: Check for folder changes and run tests
      run: |
        folders=$(cat folders.txt)
        previous_commit=${{ env.previous_commit }}
        current_commit=${{ env.current_commit }}

        echo "Checking changes between commits $previous_commit and $current_commit"

        IFS=' ' read -r -a folder_array <<< "$folders"
        for folder in "${folder_array[@]}"; do
          if git diff --name-only $previous_commit $current_commit | grep -q "^$folder/"; then
            echo "$folder has changed"
            echo "Running npm test in $folder"
            cd $folder
            npm install
            npm run test
            cd ..
          fi
        done

  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV

    - name: Get all folders
      id: get_folders
      run: |
        folders=$(find . -maxdepth 1 -type d | sed 's|./||' | grep -v '^\.$' | grep -v '.git')
        echo "folders=$folders" >> $GITHUB_ENV
        echo "folders=$folders" > folders.txt

    - name: Check for folder changes and run coverage
      run: |
        folders=$(cat folders.txt)
        previous_commit=${{ env.previous_commit }}
        current_commit=${{ env.current_commit }}

        echo "Checking changes between commits $previous_commit and $current_commit"

        IFS=' ' read -r -a folder_array <<< "$folders"
        for folder in "${folder_array[@]}"; do
          if git diff --name-only $previous_commit $current_commit | grep -q "^$folder/"; then
            echo "$folder has changed"
            echo "Running npm coverage in $folder"
            cd $folder
            npm install
            npm run coverage
            cd ..
          fi
        done
