name: Check Folder Changes

on: [push]

jobs:
  check-folder-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch all history for all branches and tags
      run: git fetch --prune --unshallow

    - name: Determine the commit range
      id: commit_range
      run: |
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)

        echo "previous_commit=$previous_commit" >> $GITHUB_ENV
        echo "current_commit=$current_commit" >> $GITHUB_ENV

    - name: Check for folder changes
      id: check_changes
      run: |
        folders=("CommonMessages" "Logger" "RedisClient" "RabbitMqClient" "Supervision")
        changed_folders=""

        echo "Checking changes between commits $previous_commit and $current_commit"

        for folder in "${folders[@]}"; do
          if git diff --name-only $previous_commit $current_commit | grep -q "^$folder/"; then
            echo "$folder has changed"
            changed_folders+="$folder "
          fi
        done

        echo "changed_folders=$changed_folders" >> $GITHUB_ENV
        echo "::set-output name=changed_folders::$(echo $changed_folders)"

    - name: Log changed folders
      run: |
        if [ -n "$changed_folders" ]; then
          echo "The following folders have changed: $changed_folders"
        else
          echo "No specified folders have changed."
        fi
      env:
        changed_folders: ${{ env.changed_folders }}

  test:
    needs: check-folder-changes
    runs-on: ubuntu-latest
    if: ${{ needs.check-folder-changes.outputs.changed_folders != '' }}
    strategy:
      matrix:
        folder: ${{ fromJson(needs.check-folder-changes.outputs.changed_folders) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        echo "Running tests in ${{ matrix.folder }}"
        cd ${{ matrix.folder }}
        npm install
        npm run test

  coverage:
    needs: check-folder-changes
    runs-on: ubuntu-latest
    if: ${{ needs.check-folder-changes.outputs.changed_folders != '' }}
    strategy:
      matrix:
        folder: ${{ fromJson(needs.check-folder-changes.outputs.changed_folders) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run coverage
      run: |
        echo "Running coverage in ${{ matrix.folder }}"
        cd ${{ matrix.folder }}
        npm install
        npm run coverage
