name: Check Folder Changes

on: [push]

jobs:
  check-folder-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check for folder changes
      id: check_changes
      run: |
        # List of folders to check
        folders=("CommonMessages" "Logger" "RedisClient" "RabbitMqClient" "Supervision")
        
        # Initialize a variable to hold changed folders
        changed_folders=""

        # Check if any of the folders have changed
        for folder in "${folders[@]}"; do
          if git diff --name-only HEAD~1 HEAD | grep -q "^$folder/"; then
            echo "$folder has changed"
            changed_folders+="$folder "
          fi
        done

        # Save the changed folders to be used in the next step
        echo "changed_folders=$changed_folders" >> $GITHUB_ENV

    - name: Log changed folders
      run: |
        if [ -n "$changed_folders" ]; then
          echo "The following folders have changed: $changed_folders"
        else
          echo "No specified folders have changed."
        fi
      env:
        changed_folders: ${{ env.changed_folders }}
